import { Icon, LatLngExpression } from 'leaflet';
import { INamedTileLayerProps } from './models';

export const MaxZoom = 19;

export const StartZoom = 10;

export const StartCoordinates: LatLngExpression = [40.98, 29.05];

export const ApiBaseUrl = 'localhost:3600';//import.meta.env.REACT_APP_TARGET_API ?? import.meta.env.VITE_TARGET_API ?? window.location.host;

export const GenericAirportIconSvg = '/image/airport/airport.svg';

export const GenericAircraftIconSvg = '/image/aircraft/airliner.svg';

export const LocationMarkerIconSvg = '/image/location.svg';

export const LocationMarkerIcon = new Icon({ iconUrl: LocationMarkerIconSvg, iconSize: [24, 24] });

export const ApiEndpoints = {
  Aircrafts: '/aircraft/seen',
  AirportTypes: '/airport/types',
  AirportInArea: '/airport/area',
  AirportInfo: '/airport/detail',
};

export const AirlineLogoSource: { [key: string]: string } = {
  FlightAware:
    'https://www.flightaware.com/images/airline_logos/180px/[ICAO].png',
  AirHex:
    'https://content.airhex.com/content/logos/airlines_[ICAO]_100_100_s.png',
  Empty: './image/grey-dot.svg',
};

export const AirportIconMap: { [key: string]: Icon } = {
  generic: new Icon({
    iconUrl: GenericAirportIconSvg,
    className: 'airport-icon-generic',
    iconSize: [15, 15],
    popupAnchor: [0, 0],
  }),
  large_airport: new Icon({
    iconUrl: '/image/airport/airport.svg',
    className: 'airport-icon-large',
    iconSize: [20, 20],
    popupAnchor: [0, 0],
  }),
  medium_airport: new Icon({
    iconUrl: '/image/airport/airport.svg',
    className: 'airport-icon-medium',
    iconSize: [17, 17],
    popupAnchor: [0, 0],
  }),
  small_airport: new Icon({
    iconUrl: '/image/airport/airport.svg',
    className: 'airport-icon-small',
    iconSize: [15, 15],
    popupAnchor: [0, 0],
  }),
  seaplane_base: new Icon({
    iconUrl: '/image/blue-dot.png',
    className: 'airport-icon-seaplane',
    iconSize: [15, 15],
    popupAnchor: [0, 0],
  }),
  heliport: new Icon({
    iconUrl: '/image/airport/heliport.svg',
    className: 'airport-icon-heliport',
    iconSize: [15, 15],
    popupAnchor: [0, 0],
  }),
  balloonport: new Icon({
    iconUrl: '/image/blue-dot.png',
    className: 'airport-icon-balloonport',
    iconSize: [15, 15],
    popupAnchor: [0, 0],
  }),
};

export const AirportTypes = [...Object.keys(AirportIconMap).map((k) => k)];

export const AircraftIconMap: { [key: string]: Icon } = {
  generic: new Icon({
    iconUrl: GenericAircraftIconSvg,
    className: 'aircraft-icon-generic',
    iconSize: [24, 24],
    popupAnchor: [0, 0],
  }),
  airliner_heavy_2e: new Icon({
    iconUrl: '/image/aircraft/airliner_heavy_2e.png',
    className: 'aircraft-icon-generic',
    iconSize: [28, 28],
    popupAnchor: [0, 0],
  }),
  airliner_heavy_4e: new Icon({
    iconUrl: '/image/aircraft/airliner_heavy_4e.png',
    className: 'aircraft-icon-generic',
    iconSize: [28, 28],
    popupAnchor: [0, 0],
  }),
  airliner: new Icon({
    iconUrl: '/image/aircraft/airliner.svg',
    className: 'aircraft-icon-airliner',
    iconSize: [24, 24],
    popupAnchor: [0, 0],
  }),
  business_jet: new Icon({
    iconUrl: '/image/aircraft/business-jet.svg',
    className: 'aircraft-icon-airliner',
    iconSize: [22, 22],
    popupAnchor: [0, 0],
  }),
  propeller_large: new Icon({
    iconUrl: '/image/aircraft/propeller-large.svg',
    className: 'aircraft-icon-airliner',
    iconSize: [24, 24],
    popupAnchor: [0, 0],
  }),
  propeller_small: new Icon({
    iconUrl: '/image/aircraft/propeller-small.svg',
    className: 'aircraft-icon-airliner',
    iconSize: [22, 22],
    popupAnchor: [0, 0],
  }),
  military: new Icon({
    iconUrl: '/image/aircraft/military.svg',
    className: 'aircraft-icon-military',
    iconSize: [20, 20],
    popupAnchor: [0, 0],
  }),
  helicopter: new Icon({
    iconUrl: '/image/aircraft/helicopter.svg',
    className: 'aircraft-icon-helicopter',
    iconSize: [20, 20],
    popupAnchor: [0, 0],
  }),
  balloon: new Icon({
    iconUrl: '/image/aircraft/balloon.svg',
    className: 'aircraft-icon-balloon',
    iconSize: [18, 18],
    popupAnchor: [0, 0],
  }),
};



export const MapLayers: INamedTileLayerProps[] = [
  {
    name: 'CartoBlack',
    props: {
      url: 'https://cartodb-basemaps-a.global.ssl.fastly.net/dark_all/{z}/{x}/{y}.png',
      maxZoom: MaxZoom,
      attribution:
        '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>',
    },
  },
  {
    name: 'CartoLight',
    props: {
      url: 'https://cartodb-basemaps-a.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png',
      maxZoom: MaxZoom,
      attribution:
        '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>',
    },
  },
  {
    name: 'OSM',
    props: {
      url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
      maxZoom: MaxZoom,
      attribution:
        '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>',
    },
  },
];

// https://github.com/flightaware/dump1090/blob/master/public_html/markers.js
export const AircraftTypeDescriptionIconMap: { [key: string]: string } = {
  'H': 'helicopter',
  'L1P': 'propeller',
  'L1T': 'propeller',
  'L1J': 'military',
  'L2P': 'propeller_small',
  'L2T': 'propeller_large',
  'L2J-L': 'business_jet',
  'L2J-M': 'airliner',
  'L2J-H': 'airliner_heavy_2e',
  'L4T': 'airliner_heavy_4e',
  'L4J-H': 'airliner_heavy_4e'
};

// https://github.com/flightaware/dump1090/blob/master/public_html/markers.js
export const AircraftCategoryIconMap = {
  'A1': 'propeller',
  'A2': 'business_jet',
  'A3': 'airliner',
  'A4': 'airliner_heavy_2e',
  'A5': 'airliner_heavy_4e',
  'A6': 'military',
  'A7': 'helicopter',
  'B1': 'propeller',
  'B2': 'balloon',
  'B4': 'propeller',
  'B7': 'military',
  'C0': 'ground_unknown',
  'C1': 'ground_emergency',
  'C2': 'ground_service',
  'C3': 'ground_fixed',
  'C4': 'ground_fixed',
  'C5': 'ground_fixed',
  'C6': 'ground_unknown',
  'C7': 'ground_unknown'
};

// https://github.com/flightaware/dump1090/blob/master/public_html/markers.js
export const AircraftTypeDesignatorIconMap: { [key: string]: string } = {
  'A10': 'military',
  'A148': 'military',
  'A225': 'heavy_4e',
  'A3': 'military',
  'A37': 'business_jet',
  'A5': 'propeller',
  'A6': 'military',
  'A700': 'business_jet',
  'AC80': 'propeller_small',
  'AC90': 'propeller_small',
  'AC95': 'propeller_small',
  'AJ27': 'business_jet',
  'AJET': 'military',
  'AN28': 'propeller_small',
  'ARCE': 'military',
  'AT3': 'military',
  'ATG1': 'business_jet',
  'B18T': 'propeller_small',
  'B190': 'propeller_small',
  'B25': 'propeller_large',
  'B350': 'propeller_small',
  'B52': 'heavy_4e',
  'B712': 'business_jet',
  'B721': 'airliner',
  'B722': 'airliner',
  'BALL': 'balloon',
  'BE10': 'propeller_small',
  'BE20': 'propeller_small',
  'BE30': 'propeller_small',
  'BE32': 'propeller_small',
  'BE40': 'business_jet',
  'BE99': 'propeller_small',
  'BE9L': 'propeller_small',
  'BE9T': 'propeller_small',
  'BN2T': 'propeller_small',
  'BPOD': 'business_jet',
  'BU20': 'propeller_small',
  'C08T': 'business_jet',
  'C125': 'propeller_small',
  'C212': 'propeller_small',
  'C21T': 'propeller_small',
  'C22J': 'business_jet',
  'C25A': 'business_jet',
  'C25B': 'business_jet',
  'C25C': 'business_jet',
  'C25M': 'business_jet',
  'C425': 'propeller_small',
  'C441': 'propeller_small',
  'C46': 'propeller_large',
  'C500': 'business_jet',
  'C501': 'business_jet',
  'C510': 'business_jet',
  'C525': 'business_jet',
  'C526': 'business_jet',
  'C550': 'business_jet',
  'C551': 'business_jet',
  'C55B': 'business_jet',
  'C560': 'business_jet',
  'C56X': 'business_jet',
  'C650': 'business_jet',
  'C680': 'business_jet',
  'C68A': 'business_jet',
  'C750': 'business_jet',
  'C82': 'propeller_large',
  'CKUO': 'military',
  'CL30': 'business_jet',
  'CL35': 'business_jet',
  'CL60': 'business_jet',
  'CRJ1': 'business_jet',
  'CRJ2': 'business_jet',
  'CRJ7': 'business_jet',
  'CRJ9': 'business_jet',
  'CRJX': 'business_jet',
  'CVLP': 'propeller_large',
  'D228': 'propeller_small',
  'DA36': 'military',
  'DA50': 'airliner',
  'DC10': 'airliner_heavy_2e',
  'DC3': 'propeller_large',
  'DC3S': 'propeller_large',
  'DHA3': 'propeller_small',
  'DHC4': 'propeller_large',
  'DHC6': 'propeller_small',
  'DLH2': 'military',
  'E110': 'propeller_small',
  'E135': 'business_jet',
  'E145': 'business_jet',
  'E29E': 'military',
  'E45X': 'business_jet',
  'E500': 'business_jet',
  'E50P': 'business_jet',
  'E545': 'business_jet',
  'E55P': 'business_jet',
  'EA50': 'business_jet',
  'EFAN': 'business_jet',
  'EFUS': 'military',
  'ELIT': 'business_jet',
  'EUFI': 'military',
  'F1': 'military',
  'F100': 'business_jet',
  'F111': 'military',
  'F117': 'military',
  'F14': 'military',
  'F15': 'military',
  'F22': 'military',
  'F2TH': 'business_jet',
  'F4': 'military',
  'F406': 'propeller_small',
  'F5': 'military',
  'F900': 'business_jet',
  'FA50': 'business_jet',
  'FA5X': 'business_jet',
  'FA7X': 'business_jet',
  'FA8X': 'business_jet',
  'FJ10': 'business_jet',
  'FOUG': 'business_jet',
  'FURY': 'military',
  'G150': 'business_jet',
  'G3': 'airliner',
  'GENI': 'military',
  'GL5T': 'business_jet',
  'GLEX': 'business_jet',
  'GLF2': 'business_jet',
  'GLF3': 'business_jet',
  'GLF4': 'business_jet',
  'GLF5': 'business_jet',
  'GLF6': 'business_jet',
  'GSPN': 'business_jet',
  'H25A': 'business_jet',
  'H25B': 'business_jet',
  'H25C': 'business_jet',
  'HA4T': 'airliner',
  'HDJT': 'business_jet',
  'HERN': 'business_jet',
  'J8A': 'military',
  'J8B': 'military',
  'JH7': 'military',
  'JS31': 'propeller_small',
  'JS32': 'propeller_small',
  'JU52': 'propeller_small',
  'L101': 'heavy_2e',
  'LAE1': 'military',
  'LEOP': 'business_jet',
  'LJ23': 'business_jet',
  'LJ24': 'business_jet',
  'LJ25': 'business_jet',
  'LJ28': 'business_jet',
  'LJ31': 'business_jet',
  'LJ35': 'business_jet',
  'LJ40': 'business_jet',
  'LJ45': 'business_jet',
  'LJ55': 'business_jet',
  'LJ60': 'business_jet',
  'LJ70': 'business_jet',
  'LJ75': 'business_jet',
  'LJ85': 'business_jet',
  'LTNG': 'military',
  'M28': 'propeller_small',
  'MD11': 'heavy_2e',
  'MD81': 'business_jet',
  'MD82': 'business_jet',
  'MD83': 'business_jet',
  'MD87': 'business_jet',
  'MD88': 'business_jet',
  'MD90': 'business_jet',
  'ME62': 'business_jet',
  'METR': 'military',
  'MG19': 'military',
  'MG25': 'military',
  'MG29': 'military',
  'MG31': 'military',
  'MG44': 'military',
  'MH02': 'business_jet',
  'MS76': 'business_jet',
  'MT2': 'military',
  'MU2': 'propeller_small',
  'P180': 'propeller_small',
  'P2': 'propeller_large',
  'P68T': 'propeller_small',
  'PA47': 'business_jet',
  'PAT4': 'propeller_small',
  'PAY1': 'propeller_small',
  'PAY2': 'propeller_small',
  'PAY3': 'propeller_small',
  'PAY4': 'propeller_small',
  'PIAE': 'military',
  'PIT4': 'military',
  'PITE': 'military',
  'PRM1': 'business_jet',
  'PRTS': 'business_jet',
  'Q5': 'military',
  'R721': 'airliner',
  'R722': 'airliner',
  'RFAL': 'military',
  'ROAR': 'military',
  'S3': 'military',
  'S32E': 'military',
  'S37': 'military',
  'S601': 'business_jet',
  'SATA': 'business_jet',
  'SB05': 'business_jet',
  'SC7': 'propeller_small',
  'SF50': 'business_jet',
  'SJ30': 'business_jet',
  'SLCH': 'heavy_4e',
  'SM60': 'propeller_small',
  'SOL1': 'business_jet',
  'SOL2': 'business_jet',
  'SP33': 'business_jet',
  'SR71': 'military',
  'SS2': 'military',
  'SU15': 'military',
  'SU24': 'military',
  'SU25': 'military',
  'SU27': 'military',
  'SW2': 'propeller_small',
  'SW3': 'propeller_small',
  'SW4': 'propeller_small',
  'T154': 'airliner',
  'T2': 'business_jet',
  'T22M': 'military',
  'T37': 'business_jet',
  'T38': 'business_jet',
  'T4': 'military',
  'TJET': 'business_jet',
  'TOR': 'military',
  'TRIM': 'propeller_small',
  'TRIS': 'propeller_small',
  'TRMA': 'propeller_small',
  'TU22': 'military',
  'VAUT': 'military',
  'Y130': 'military',
  'Y141': 'airliner',
  'YK28': 'military',
  'YK38': 'airliner',
  'YK40': 'airliner',
  'YK42': 'airliner',
  'YURO': 'military'
};
